### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by colorpride** [FinchSec/kismet-docker#2]
I would like to see the use of docker compose, but I don't have enough knowledge.
If the author makes a docker compose, I will be very grateful

**Comment by colorpride** [comment]
split request

**Comment by tomdot-dev** [comment]
These are two separate issues, and GPSD support should be moved to its own and if you could elaborate what you mean by GPSd support, that would be great because kismet supports GPSd. Once you do that, I'll address it.

Docker compose is merely adapting the command line to a YAML format. Could you elaborate your use case for Docker compose?

**Comment by colorpride** [comment]
It is good form to support docker-compose for running the container as a service with the ability to connect volumes

https://github.com/kismetwireless/kismet-packages/tree/master/docker
this will also be useful for connecting custom kismet_site.conf and others

**Comment by colorpride** [comment]
https://github.com/kismetwireless/kismet-packages/tree/master/docker

**Comment by colorpride** [comment]
также это будет полезно для подключения custom kismet_site.conf и другого

**Comment by tomdot-dev** [comment]
That docker compose file you reference is merely to build kismet packages.

You can connect volumes by using `-v` parameter in `docker run`.

**Comment by colorpride** [comment]
your repository - your rules.

**Comment by tomdot-dev** [comment]
I'll add a reference docker compose file.

**Comment by dimage** [comment]
I want your repository to develop, and I am writing to you about my wishes as a user.
I wish your repository all the best

**Comment by tomdot-dev** [comment]
e797b0761ebf68276f2cde96b09a1acd7f52f75d

**Comment by tomdot-dev** [comment]
I used https://www.composerize.com/ to help converting the command line to docker-compose.
